name: Run AI Crew

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches: [ main ]  # This line specifies the branch
  workflow_dispatch:  # Keeps manual trigger option

jobs:
  run-crew:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install crewai langchain openai

    - name: Run CrewAI script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python .github/run_crew.py

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ai_summary.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update AI summary" -a && git push)
